### ISSUE TITLE
What is the future of this project?

### ISSUE THREAD

**Issue by fabianmoronzirfas** [na-boa/brightsky#62]
Great project. Very very useful for the open data community. Thank you. 

We are often using dwd data and had to scrape the ftp ourselves to get some data. 

So the question is. What is the roadmap for this project? How is the DWD involved? And if this an official project?

**Comment by jdemaeyer** [comment]
Heyho Fabian, thanks a lot for the kind words and for reaching out!

This is not an official DWD project nor is the DWD currently involved. However, Bright Sky is publicly funded through the Open Knowledge Foundation's [Prototype Fund](https://prototypefund.de/). I am currently the sole developer and will be devoting most of my time towards it until the end of August. While I will have to earn my bread doing other work afterwards, I plan to keep maintaining it and will keep it available and free-for-use.

We have reached most of our "set in stone" milestones with the public availability of the API last week. The second half of the funding period will be geared towards smoothening some rough edges and gathering/incorporating feedback. In particular, I would like to

- stress-test and harden the production deployment,
- add meteorological elements currently publicized by the DWD but not available in Bright Sky,
- add a "current weather" endpoint with some interpolation magic,
- provide Python and Docker packages, and
- (what else) improve test coverage.

But this is just a rough wish list, and I'm very open to shifting my focus based on community feedback.

**Comment by fabianmoronzirfas** [comment]
Great to hear that. I know that the DWD is trying to improve their open data setup. Maybe you should try to get in contact with them? I've been in contact with a researcher who worked for them on this topic. If you DM (see my profile) me I can try to get you in touch.
